import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-tool-pdf",
    "text-tool-pdf",
    "border-tool-pdf",
    "bg-tool-image",
    "text-tool-image",
    "border-tool-image",
    "bg-tool-photo",
    "text-tool-photo",
    "border-tool-photo",
    "bg-tool-convert",
    "text-tool-convert",
    "border-tool-convert",
    "bg-tool-word",
    "text-tool-word",
    "border-tool-word",
    "bg-tool-img2pdf",
    "text-tool-img2pdf",
    "border-tool-img2pdf",
    "bg-surface-base",
    "bg-surface-card",
    "bg-surface-elevated",
    "text-content-primary",
    "text-content-secondary",
    "text-content-muted",
    "border-surface-border",
    "text-brand-blue",
    "bg-brand-blue",
    "bg-tool-pdf/10",
    "bg-tool-pdf/15",
    "bg-tool-image/15",
    "bg-tool-photo/15",
    "bg-tool-convert/15",
    "bg-tool-word/15",
    "bg-tool-img2pdf/15",
    "bg-brand-blue/10",
    "bg-brand-blue/15",
    "border-brand-blue/30",
    "hover:bg-tool-pdf/10",
    "hover:border-brand-blue",
    "hover:bg-surface-elevated",
    "text-brand-blue-light",
  ],
  theme: {
    extend: {
      colors: {
        "surface-base": "#0A0F1E",
        "surface-card": "#111827",
        "surface-elevated": "#1A2235",
        "surface-border": "#1F2D45",
        "content-primary": "#F0F4FF",
        "content-secondary": "#8B9ABB",
        "content-muted": "#4A5568",
        "brand-blue": "#3B82F6",
        "brand-blue-light": "#60A5FA",
        "tool-pdf": "#EF4444",
        "tool-image": "#8B5CF6",
        "tool-photo": "#F59E0B",
        "tool-convert": "#10B981",
        "tool-word": "#3B82F6",
        "tool-img2pdf": "#EC4899",
      },
    },
  },
  plugins: [],
};

export default config;
