import {
  ArrowLeftRight,
  Cake,
  Calculator,
  CalendarDays,
  Eraser,
  FileBadge,
  FileDown,
  FileImage,
  FilePlus,
  FileText,
  GraduationCap,
  ImageDown,
  Images,
  IndianRupee,
  KeyRound,
  LineChart,
  LockOpen,
  PenLine,
  Percent,
  PiggyBank,
  QrCode,
  Receipt,
  RefreshCw,
  Ruler,
  ScanLine,
  Scissors,
  Scale,
  TrendingUp,
  Wallet,
  WholeWord,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { ToolAccent } from "@/components/ToolCard";

export type ToolFilterCategory = "pdf" | "images" | "convert";

export const ALL_TOOLS = [
  {
    slug: "pdf-compress",
    name: "PDF Compress",
    description: "Reduce PDF file size instantly",
    href: "/tools/pdf-compress",
    icon: "FileDown",
    color: "#EF4444",
    bgClass: "bg-tool-pdf/10",
    textClass: "text-tool-pdf",
    borderClass: "border-tool-pdf",
    category: "PDF",
  },
  {
    slug: "pdf-merge",
    name: "PDF Merge",
    description: "Combine multiple PDFs into one",
    href: "/tools/pdf-merge",
    icon: "FilePlus",
    color: "#EF4444",
    bgClass: "bg-tool-pdf/10",
    textClass: "text-tool-pdf",
    borderClass: "border-tool-pdf",
    category: "PDF",
  },
  {
    slug: "pdf-split",
    name: "PDF Split",
    description: "Extract pages from a PDF",
    href: "/tools/pdf-split",
    icon: "Scissors",
    color: "#EF4444",
    bgClass: "bg-tool-pdf/10",
    textClass: "text-tool-pdf",
    borderClass: "border-tool-pdf",
    category: "PDF",
  },
  {
    slug: "pdf-unlock",
    name: "Remove PDF Password",
    description: "Remove password from protected PDF",
    href: "/tools/pdf-unlock",
    icon: "LockOpen",
    color: "#EF4444",
    bgClass: "bg-tool-pdf/10",
    textClass: "text-tool-pdf",
    borderClass: "border-tool-pdf",
    category: "PDF",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to JPG images",
    href: "/tools/pdf-to-jpg",
    icon: "FileImage",
    color: "#EF4444",
    bgClass: "bg-tool-pdf/10",
    textClass: "text-tool-pdf",
    borderClass: "border-tool-pdf",
    category: "PDF",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to editable Word document",
    href: "/tools/pdf-to-word",
    icon: "FileText",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "PDF",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word document to PDF",
    href: "/tools/word-to-pdf",
    icon: "FileBadge",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "PDF",
  },
  {
    slug: "image-compress",
    name: "Image Compress",
    description: "Compress images without quality loss",
    href: "/tools/image-compress",
    icon: "ImageDown",
    color: "#8B5CF6",
    bgClass: "bg-tool-image/10",
    textClass: "text-tool-image",
    borderClass: "border-tool-image",
    category: "Images",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPG, PNG, WebP",
    href: "/tools/image-converter",
    icon: "RefreshCw",
    color: "#8B5CF6",
    bgClass: "bg-tool-image/10",
    textClass: "text-tool-image",
    borderClass: "border-tool-image",
    category: "Images",
  },
  {
    slug: "bg-remove",
    name: "Background Remover",
    description: "Remove background from any image",
    href: "/tools/bg-remove",
    icon: "Eraser",
    color: "#8B5CF6",
    bgClass: "bg-tool-image/10",
    textClass: "text-tool-image",
    borderClass: "border-tool-image",
    category: "Images",
  },
  {
    slug: "photo-resizer",
    name: "Photo Resizer",
    description: "Resize to Aadhaar, PAN, Passport size",
    href: "/tools/photo-resizer",
    icon: "ScanLine",
    color: "#F59E0B",
    bgClass: "bg-tool-photo/10",
    textClass: "text-tool-photo",
    borderClass: "border-tool-photo",
    category: "Images",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Combine images into a single PDF",
    href: "/tools/image-to-pdf",
    icon: "Images",
    color: "#EC4899",
    bgClass: "bg-tool-img2pdf/10",
    textClass: "text-tool-img2pdf",
    borderClass: "border-tool-img2pdf",
    category: "Images",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and reading time",
    href: "/tools/word-counter",
    icon: "WholeWord",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Text",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age from date of birth",
    href: "/tools/age-calculator",
    icon: "Cake",
    color: "#F59E0B",
    bgClass: "bg-tool-photo/10",
    textClass: "text-tool-photo",
    borderClass: "border-tool-photo",
    category: "Utility",
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create QR codes for URL, WiFi, VCard, WhatsApp, and more",
    href: "/tools/qr-code-generator",
    icon: "QrCode",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate home, car, and personal loan EMI",
    href: "/tools/emi-calculator",
    icon: "IndianRupee",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description: "Add or remove GST with CGST and SGST split",
    href: "/tools/gst-calculator",
    icon: "Percent",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
  {
    slug: "salary-hike-calculator",
    name: "Salary Hike Calculator",
    description: "Calculate new salary after appraisal hike",
    href: "/tools/salary-hike-calculator",
    icon: "TrendingUp",
    color: "#F59E0B",
    bgClass: "bg-tool-photo/10",
    textClass: "text-tool-photo",
    borderClass: "border-tool-photo",
    category: "Utility",
  },
  {
    slug: "cgpa-to-percentage",
    name: "CGPA to Percentage",
    description: "Convert CGPA to percentage for VTU, CBSE, and more",
    href: "/tools/cgpa-to-percentage",
    icon: "GraduationCap",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "ctc-calculator",
    name: "CTC to In-Hand Salary",
    description: "Estimate monthly take-home pay from annual CTC",
    href: "/tools/ctc-calculator",
    icon: "Wallet",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    description: "Calculate fixed deposit maturity and interest",
    href: "/tools/fd-calculator",
    icon: "PiggyBank",
    color: "#F59E0B",
    bgClass: "bg-tool-photo/10",
    textClass: "text-tool-photo",
    borderClass: "border-tool-photo",
    category: "Utility",
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    description: "Calculate mutual fund SIP returns and maturity",
    href: "/tools/sip-calculator",
    icon: "LineChart",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
  {
    slug: "notice-period-calculator",
    name: "Notice Period Calculator",
    description: "Find your last working day and buyout amount",
    href: "/tools/notice-period-calculator",
    icon: "CalendarDays",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate % of number, change, and more",
    href: "/tools/percentage-calculator",
    icon: "Percent",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Create strong random passwords instantly",
    href: "/tools/password-generator",
    icon: "KeyRound",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, and more",
    href: "/tools/unit-converter",
    icon: "Ruler",
    color: "#F59E0B",
    bgClass: "bg-tool-photo/10",
    textClass: "text-tool-photo",
    borderClass: "border-tool-photo",
    category: "Utility",
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax Calculator",
    description: "Compare old vs new regime tax for FY 2025-26",
    href: "/tools/income-tax-calculator",
    icon: "Scale",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "signature-maker",
    name: "Signature Maker",
    description: "Draw, type, or upload digital signatures",
    href: "/tools/signature-maker",
    icon: "PenLine",
    color: "#3B82F6",
    bgClass: "bg-brand-blue/10",
    textClass: "text-brand-blue",
    borderClass: "border-brand-blue",
    category: "Utility",
  },
  {
    slug: "rent-receipt-generator",
    name: "Rent Receipt Generator",
    description: "Create and download rent receipt PDFs",
    href: "/tools/rent-receipt-generator",
    icon: "Receipt",
    color: "#10B981",
    bgClass: "bg-tool-convert/10",
    textClass: "text-tool-convert",
    borderClass: "border-tool-convert",
    category: "Utility",
  },
] as const;

export const RELATED_TOOLS: Record<string, string[]> = {
  "pdf-compress": ["pdf-merge", "pdf-split", "pdf-to-word"],
  "pdf-to-word": ["word-to-pdf", "word-counter", "pdf-compress"],
  "word-to-pdf": ["pdf-to-word", "word-counter", "pdf-compress"],
  "image-compress": ["photo-resizer", "bg-remove", "image-to-pdf"],
  "photo-resizer": ["image-compress", "bg-remove", "image-converter"],
  "image-to-pdf": ["pdf-merge", "image-compress", "image-converter"],
  "bg-remove": ["image-compress", "photo-resizer", "image-converter"],
  "pdf-merge": ["pdf-split", "pdf-compress", "pdf-to-word"],
  "pdf-split": ["pdf-merge", "pdf-compress", "pdf-to-jpg"],
  "pdf-unlock": ["pdf-compress", "pdf-merge", "pdf-split"],
  "image-converter": ["image-compress", "photo-resizer", "image-to-pdf"],
  "pdf-to-jpg": ["pdf-split", "pdf-compress", "image-converter"],
  "word-counter": ["word-to-pdf", "pdf-to-word", "pdf-compress"],
  "age-calculator": ["word-counter", "photo-resizer", "pdf-compress"],
  "qr-code-generator": ["word-counter", "image-converter", "word-to-pdf"],
  "emi-calculator": ["fd-calculator", "ctc-calculator", "salary-hike-calculator"],
  "gst-calculator": ["emi-calculator", "ctc-calculator", "fd-calculator"],
  "salary-hike-calculator": ["ctc-calculator", "emi-calculator", "age-calculator"],
  "cgpa-to-percentage": ["age-calculator", "word-counter", "salary-hike-calculator"],
  "ctc-calculator": ["salary-hike-calculator", "emi-calculator", "fd-calculator"],
  "fd-calculator": ["emi-calculator", "ctc-calculator", "gst-calculator"],
  "sip-calculator": ["fd-calculator", "emi-calculator", "salary-hike-calculator"],
  "notice-period-calculator": ["ctc-calculator", "salary-hike-calculator", "age-calculator"],
  "percentage-calculator": ["gst-calculator", "salary-hike-calculator", "emi-calculator"],
  "password-generator": ["qr-code-generator", "word-counter", "age-calculator"],
  "unit-converter": ["percentage-calculator", "age-calculator", "gst-calculator"],
  "income-tax-calculator": ["ctc-calculator", "salary-hike-calculator", "gst-calculator"],
  "signature-maker": ["word-to-pdf", "pdf-merge", "qr-code-generator"],
  "rent-receipt-generator": ["income-tax-calculator", "ctc-calculator", "salary-hike-calculator"],
};

export const TOOL_ICONS: Record<string, LucideIcon> = {
  FileDown,
  FilePlus,
  Scissors,
  LockOpen,
  FileImage,
  ImageDown,
  RefreshCw,
  Eraser,
  ScanLine,
  FileText,
  FileBadge,
  Images,
  WholeWord,
  Cake,
  QrCode,
  Wrench,
  Calculator,
  IndianRupee,
  Percent,
  TrendingUp,
  GraduationCap,
  Wallet,
  PiggyBank,
  LineChart,
  CalendarDays,
  KeyRound,
  Ruler,
  ArrowLeftRight,
  Scale,
  PenLine,
  Receipt,
};

export const TOOL_UI_META: Record<
  string,
  { accent: ToolAccent; filterCategory: ToolFilterCategory; popular?: boolean }
> = {
  "pdf-compress": { accent: "pdf", filterCategory: "pdf", popular: true },
  "pdf-merge": { accent: "pdf", filterCategory: "pdf" },
  "pdf-split": { accent: "pdf", filterCategory: "pdf" },
  "pdf-unlock": { accent: "pdf", filterCategory: "pdf" },
  "pdf-to-jpg": { accent: "pdf", filterCategory: "pdf" },
  "pdf-to-word": { accent: "blue", filterCategory: "convert" },
  "word-to-pdf": { accent: "convert", filterCategory: "convert" },
  "image-compress": { accent: "image", filterCategory: "images" },
  "image-converter": { accent: "image", filterCategory: "images" },
  "bg-remove": { accent: "image", filterCategory: "images" },
  "photo-resizer": { accent: "photo", filterCategory: "images" },
  "image-to-pdf": { accent: "pink", filterCategory: "convert" },
  "word-counter": { accent: "blue", filterCategory: "convert", popular: true },
  "age-calculator": { accent: "photo", filterCategory: "convert" },
  "qr-code-generator": { accent: "convert", filterCategory: "convert", popular: true },
  "emi-calculator": { accent: "blue", filterCategory: "convert", popular: true },
  "gst-calculator": { accent: "convert", filterCategory: "convert" },
  "salary-hike-calculator": { accent: "photo", filterCategory: "convert" },
  "cgpa-to-percentage": { accent: "blue", filterCategory: "convert" },
  "ctc-calculator": { accent: "convert", filterCategory: "convert", popular: true },
  "fd-calculator": { accent: "photo", filterCategory: "convert" },
  "sip-calculator": { accent: "convert", filterCategory: "convert", popular: true },
  "notice-period-calculator": { accent: "blue", filterCategory: "convert" },
  "percentage-calculator": { accent: "blue", filterCategory: "convert" },
  "password-generator": { accent: "convert", filterCategory: "convert", popular: true },
  "unit-converter": { accent: "photo", filterCategory: "convert" },
  "income-tax-calculator": { accent: "blue", filterCategory: "convert", popular: true },
  "signature-maker": { accent: "blue", filterCategory: "convert" },
  "rent-receipt-generator": { accent: "convert", filterCategory: "convert", popular: true },
};

export function getToolBySlug(slug: string) {
  return ALL_TOOLS.find((tool) => tool.slug === slug);
}

/** Optional display name overrides for the header mega menu */
export const HEADER_MENU_DISPLAY_NAMES: Partial<Record<string, string>> = {};

export const COMING_SOON_TOOL_SLUGS = new Set([
  "pdf-compress",
  "pdf-to-word",
  "pdf-to-jpg",
  "pdf-unlock",
  "bg-remove",
]);

export type MegaMenuItemConfig = {
  slug: string;
  description: string;
  comingSoon?: boolean;
  displayName?: string;
};

export type MegaMenuCategoryConfig = {
  id: string;
  title: string;
  emoji: string;
  items: MegaMenuItemConfig[];
};

export const MEGA_MENU_CATEGORIES: MegaMenuCategoryConfig[] = [
  {
    id: "pdf",
    title: "PDF Tools",
    emoji: "📄",
    items: [
      { slug: "pdf-merge", description: "Combine multiple PDFs into one" },
      { slug: "pdf-split", description: "Extract pages from PDF" },
      { slug: "pdf-compress", description: "Reduce PDF file size", comingSoon: true },
      { slug: "pdf-to-word", description: "Convert PDF to editable Word", comingSoon: true },
      { slug: "pdf-to-jpg", description: "Convert PDF pages to images", comingSoon: true },
      {
        slug: "pdf-unlock",
        description: "Unlock password protected PDF",
        comingSoon: true,
      },
    ],
  },
  {
    id: "image",
    title: "Image Tools",
    emoji: "🖼️",
    items: [
      { slug: "image-compress", description: "Reduce image file size" },
      { slug: "photo-resizer", description: "Resize to exact dimensions" },
      { slug: "bg-remove", description: "Remove image background", comingSoon: true },
      { slug: "image-to-pdf", description: "Convert images to PDF" },
      { slug: "image-converter", description: "Convert between JPG, PNG, WebP" },
    ],
  },
  {
    id: "document",
    title: "Document Tools",
    emoji: "📝",
    items: [
      { slug: "word-to-pdf", description: "Convert Word documents to PDF" },
      { slug: "signature-maker", description: "Create digital signature" },
      { slug: "rent-receipt-generator", description: "Generate rent receipts PDF" },
    ],
  },
  {
    id: "finance",
    title: "Finance Calculators",
    emoji: "🧮",
    items: [
      { slug: "emi-calculator", description: "Calculate loan EMI instantly" },
      { slug: "gst-calculator", description: "Add or remove GST" },
      { slug: "sip-calculator", description: "Calculate mutual fund returns" },
      { slug: "fd-calculator", description: "Calculate fixed deposit returns" },
      { slug: "ctc-calculator", description: "Know your in-hand salary" },
      { slug: "salary-hike-calculator", description: "Calculate new salary after hike" },
      { slug: "income-tax-calculator", description: "Old vs New regime comparison" },
    ],
  },
  {
    id: "student",
    title: "Student Tools",
    emoji: "🎓",
    items: [
      { slug: "cgpa-to-percentage", description: "Convert CGPA to percentage" },
      { slug: "percentage-calculator", description: "Calculate percentages easily" },
      { slug: "word-counter", description: "Count words and characters" },
      { slug: "age-calculator", description: "Calculate exact age" },
    ],
  },
  {
    id: "utility",
    title: "Utility Tools",
    emoji: "⚙️",
    items: [
      { slug: "qr-code-generator", description: "Generate QR codes free" },
      { slug: "password-generator", description: "Create strong passwords" },
      { slug: "unit-converter", description: "Convert length, weight, temp" },
      { slug: "notice-period-calculator", description: "Find your last working day" },
    ],
  },
];

/** @deprecated Use MEGA_MENU_CATEGORIES via getMegaMenuCategories() */
export const HEADER_MENU_CATEGORIES = MEGA_MENU_CATEGORIES.map((category) => ({
  title: category.title,
  icon: "Wrench" as const,
  iconClassName: "text-tool-convert",
  slugs: category.items.map((item) => item.slug),
}));

export type MegaMenuTool = {
  tool: (typeof ALL_TOOLS)[number];
  description: string;
  displayName?: string;
  comingSoon: boolean;
};

export type MegaMenuCategory = MegaMenuCategoryConfig & {
  tools: MegaMenuTool[];
};

export function getMegaMenuCategories(): MegaMenuCategory[] {
  return MEGA_MENU_CATEGORIES.map((category) => ({
    ...category,
    tools: category.items.flatMap((item) => {
      const tool = getToolBySlug(item.slug);
      if (!tool) return [];

      return [
        {
          tool,
          description: item.description,
          displayName: item.displayName ?? HEADER_MENU_DISPLAY_NAMES[item.slug],
          comingSoon:
            item.comingSoon ?? COMING_SOON_TOOL_SLUGS.has(item.slug),
        },
      ];
    }),
  }));
}

export function getHeaderMenuCategories() {
  return getMegaMenuCategories();
}
