/** Meta descriptions from tool layout.tsx — used for SoftwareApplication JSON-LD */
export const TOOL_PAGE_DESCRIPTIONS: Record<string, string> = {
  "age-calculator": "Calculate exact age from date of birth instantly. Get age in years, months, days, hours, and check govt exam cutoff eligibility. Free, no signup.",
  "aspect-ratio": "Calculate image aspect ratios and resize dimensions free online. Find width or height for any aspect ratio instantly.",
  "audio-recorder": "Free online audio recorder. Record from your microphone in the browser, play back, and download instantly. No app download or signup required.",
  "base64": "Encode and decode Base64 text or files free online. Fast, private, browser-only Base64 converter.",
  "bg-remove": "Remove image backgrounds free online. AI-powered, 100% in-browser — no uploads, no server, no account needed.",
  "binary-converter": "Convert between binary, decimal, hexadecimal and octal number systems free online. Instant conversion.",
  "bmi-calculator": "Calculate your BMI free online. Supports metric and imperial units. Get instant BMI category results.",
  "box-breathing": "Free box breathing timer with animated guide. Practice the 4-4-4-4 breathing technique to reduce stress instantly. No signup, runs in your browser.",
  "calorie-deficit-calculator": "Free calorie deficit calculator using the Mifflin-St Jeor formula. Calculate your BMR, maintenance calories, and a sustainable daily target.",
  "capital-gains-calculator": "Calculate STCG and LTCG tax on shares, mutual funds, property, and gold in India. Auto-classifies by holding period with Budget 2024 rates. Free, no signup.",
  "cgpa-to-percentage": "Convert CGPA to percentage using VTU, CBSE, Anna University, and 4-point scale formulas. Reverse percentage-to-CGPA converter included. Free for students.",
  "character-counter": "Count characters, words, sentences and paragraphs free online. Real-time counting with no signup required.",
  "color-contrast": "Check color contrast ratios for WCAG accessibility compliance free online. Test foreground and background colors.",
  "color-palette-extractor": "Extract a color palette from any image free online. Get HEX and RGB codes for dominant colors. Great for design, branding, and CSS. No signup.",
  "color-picker": "Pick colors and get HEX, RGB, HSL values free online. Color palette generator and converter tool.",
  "compound-interest": "Calculate compound interest growth free online. See how your investment grows with monthly or yearly compounding.",
  "csv-to-json": "Convert CSV data to JSON format free online. Paste CSV or upload a file. Instant conversion with preview.",
  "cron-generator": "Generate and explain cron expressions with a visual builder. See next 5 run times, human-readable description, and common presets. No signup.",
  "ctc-calculator": "Calculate monthly in-hand salary from annual CTC with PF, professional tax, and income tax estimates. Free take-home pay calculator for Indian employees.",
  "days-between-dates": "Calculate the exact number of days between two dates free online. Count days until an event or days since a past date. No signup needed.",
  "device-info": "Check your browser, OS, screen resolution, and device details online free. Useful for bug reports and troubleshooting. No signup needed.",
  "discount-calculator": "Calculate discount amount and final price free online. Find percentage off and savings instantly.",
  "emi-calculator": "Free EMI calculator for home loan, car loan, and personal loan in India. Enter loan amount, rate, and tenure — get instant EMI, total interest, and payment schedule.",
  "epf-calculator": "Calculate EPF maturity amount free online. Estimate your Employee Provident Fund growth with employer and employee contributions.",
  "excel-to-pdf": "Convert Excel spreadsheets to PDF free online. No signup, browser-only Excel to PDF conversion. Fast and private.",
  "favicon-generator": "Generate a favicon from any image free online. Get favicon.ico plus all standard PNG sizes and ready-to-paste HTML tags. No signup needed.",
  "fd-calculator": "Calculate fixed deposit maturity amount, interest earned, and effective annual rate with quarterly or yearly compounding. Free FD calculator for India.",
  "gpa-calculator": "Free GPA calculator for US students. Add courses, grades, and credit hours to calculate your weighted GPA on a 4.0 scale instantly. No signup.",
  "gratuity-calculator": "Calculate gratuity amount on retirement or resignation free online. As per Payment of Gratuity Act formula.",
  "gst-calculator": "Calculate GST with CGST and SGST split for any amount in India. Add or remove 5%, 12%, 18%, or 28% GST instantly. Free online GST calculator for India.",
  "glassmorphism-generator": "Generate glassmorphism CSS with live preview. Copy pure CSS, Tailwind classes, or CSS variables with Firefox fallback. Blur, transparency, border controls.",
  "hash-generator": "Generate MD5, SHA-1, SHA-256, SHA-512 hashes free online. Fast, private, browser-only hash generator.",
  "htaccess-generator": "Generate .htaccess rules for HTTPS redirects, caching, GZIP, error pages, and IP blocking. Copy or download your .htaccess file instantly. No signup.",
  "nps-calculator": "Calculate NPS retirement corpus, monthly pension, and Section 80CCD tax savings free online. Year-by-year growth table for National Pension System India.",
  "401k-calculator": "Project your 401k balance at retirement with 2026 IRS limits, employer match, and year-by-year growth. Free retirement savings calculator — no signup.",
  "leave-encashment-calculator": "Calculate leave encashment amount and tax exemption at retirement. Budget 2023 ₹25 lakh exemption. Private and government sector formulas. Free, no signup.",
  "box-shadow-generator": "Generate multi-layer CSS box shadows with live preview. Copy pure CSS or Tailwind classes. Apple-style presets included. Free, no signup.",
  "cagr-calculator": "Calculate CAGR, future investment value, or required growth rate free online. Compare returns across mutual funds, stocks, FD and gold. No signup.",
  "ssy-calculator": "Calculate Sukanya Samriddhi Yojana maturity amount and interest at 8.2% rate. SSY year-by-year growth, partial withdrawal at 18, EEE tax benefits. No signup.",
  "advance-tax-calculator": "Calculate advance tax liability and installment schedule for FY 2026-27. Check eligibility, due dates (June/Sep/Dec/March), and penalty rules. Free, no signup.",
  "color-palette-generator": "Generate a Tailwind 50-950 color palette from any hex color. Copy tailwind.config.js or CSS variables. WCAG contrast check included. Free, no signup.",
  "professional-tax-calculator": "Calculate professional tax for all 18 Indian states free online. State-wise slabs, Maharashtra women's exemption, February quirk explained. No signup.",
  "pay-stub-generator": "Generate a professional US pay stub online free. Enter earnings and deductions, preview instantly, save as PDF. Nothing uploaded to servers. No signup.",
  "markdown-table": "Generate Markdown tables with a visual editor or paste CSV data. Align columns, add rows, copy markdown or HTML. Free, no signup, runs in browser.",
  "http-status-codes": "Complete HTTP status code reference with practical context. 1xx-5xx codes explained with causes, examples, and what to do. Searchable developer reference.",
  "401k-vs-roth-ira": "Compare Traditional 401k, Roth 401k, and Roth IRA for your retirement. See which saves more based on your tax brackets. 2026 limits, no-RMD Roth benefit. Free.",
  "bonus-calculator": "Calculate statutory bonus under Payment of Bonus Act 1965. Check eligibility (₹21,000 limit), wage ceiling (₹7,000), minimum 8.33% and maximum 20% bonus. Free.",
  "esi-calculator": "Calculate ESI contribution — employee 0.75% and employer 3.25% of gross wages. Check ₹21,000 eligibility. Understand ESI benefits. Free, no signup.",
  "swp-calculator": "Calculate how long your investment corpus will last with monthly SWP withdrawals, or how much corpus you need for a target monthly income. Free SWP calculator.",
  "heic-to-jpg": "Convert iPhone HEIC photos to JPG free online. No signup, no server upload. Fast HEIC to JPG conversion in your browser.",
  "hourly-to-salary": "Convert hourly wage to annual, monthly, or weekly salary free online. Calculate your yearly income instantly.",
  "hra-calculator": "Calculate HRA exemption for income tax free online. Find exempt and taxable HRA as per Indian tax rules.",
  "html-entity": "Encode and decode HTML entities free online. Convert special characters to HTML-safe entities instantly.",
  "image-compress": "Compress JPG, PNG, and WebP images online free. Reduce file size up to 80% without visible quality loss. No signup, nothing uploaded to a server.",
  "image-converter": "Convert images between JPG, PNG, and WebP free online. Adjust quality, see file size reduction, and download instantly. No signup, nothing uploaded.",
  "image-to-pdf": "Convert and combine JPG, PNG images into a single PDF online free. No signup, instant download, browser-only.",
  "income-tax-calculator": "Compare income tax under old and new regime for FY 2025-26. Free calculator with slab breakdown, rebates, and estimated take-home pay for salaried employees.",
  "freelancer-tax-calculator": "Calculate Section 44ADA presumptive tax for Indian freelancers free online. Compare 44ADA vs regular books, check eligibility, and estimate advance tax under new or old regime.",
  "labour-code-calculator": "Calculate New Labour Code 2026 salary impact free online. Compare current vs 50% basic structure — take-home, PF, and gratuity changes for Indian employees.",
  "inflation-calculator": "Calculate the value of money over time adjusted for inflation free online. See purchasing power changes instantly.",
  "json-formatter": "Format, beautify and validate JSON online free. Minify JSON, fix errors, and view structured data instantly.",
  "jwt-decoder": "Decode and verify JWT signatures free online. Color-coded header, payload, and signature with claims explainer. Browser-only — your secret never leaves this page.",
  "keyword-density": "Check keyword density and frequency in your content free online. Optimize your text for SEO instantly.",
  "leap-year-checker": "Check if any year is a leap year free online. See the exact rule explained, plus the next and previous leap years. No signup needed.",
  "lorem-ipsum": "Generate lorem ipsum placeholder text free online. Choose paragraphs, sentences, or words. Copy instantly.",
  "lta-calculator": "Calculate LTA tax exemption free online. Find exempt and taxable Leave Travel Allowance amount.",
  "tax-regime-comparison": "Compare old vs new tax regime side by side free online. Enter salary once — see HRA, 80C, 80D impact and which regime saves more for FY 2026-27.",
  "markdown-to-html": "Convert Markdown to HTML free online. Live preview, syntax highlighting, copy HTML instantly.",
  "morse-code": "Convert text to Morse code and back free online. Learn Morse code with instant translation.",
  "mortgage-calculator": "Free mortgage calculator with full amortization schedule. See monthly payment, PMI, taxes, insurance, and how extra payments save you money. No signup.",
  "notice-period-calculator": "Calculate your last working day from resignation date and notice period length. Includes buyout estimate and working-day calendar. Free for Indian employees.",
  "number-to-words": "Convert numbers to words in English free online. Supports Indian and International number systems.",
  "password-generator": "Generate strong random passwords or memorable passphrases with zxcvbn strength meter. Bulk generate, session history, ambiguous character exclusion. Free, browser-only.",
  "paycheck-calculator": "Free 2026 paycheck calculator. Estimate your take-home pay after federal tax, FICA, and deductions. Based on current IRS tax brackets. No signup.",
  "w2-vs-1099-calculator": "See how much you need to earn as a 1099 contractor to match your W-2 take-home pay. Compare self-employment taxes, benefits, and net income. Free, no signup.",
  "self-employment-tax": "Calculate your 1099 self-employment tax for 2026. See SE tax, income tax, total tax burden, and quarterly payment amounts with due dates. Free, no signup.",
  "pdf-compress": "Compress PDF files online for free. Reduce PDF size without losing quality. No upload, no signup — runs entirely in your browser.",
  "pdf-merge": "Merge multiple PDF files into one online free. No signup, no upload to server. Combine PDFs instantly in your browser.",
  "pdf-page-numbers": "Add page numbers to any PDF online free. Choose position, starting number, and format like 'Page 1 of 10'. No signup, nothing uploaded.",
  "pdf-rotate": "Rotate PDF pages online free — fix sideways or upside-down scanned pages. Rotate individual pages or the whole document. No signup, no uploads.",
  "pdf-split": "Split PDF files online free. Extract specific pages or split into individual pages. Browser-only, no server upload.",
  "pdf-to-jpg": "Convert PDF pages to JPG images free online. Extract each page as a high-quality image. No signup, browser-only.",
  "pdf-to-word": "Convert PDF to editable Word document online free. Fast, accurate PDF to DOCX conversion. No signup, runs in browser.",
  "pdf-unlock": "Remove password from protected PDF files free online. Unlock PDF instantly in your browser. No signup required.",
  "pdf-watermark": "Add a text or image watermark to any PDF online free. Mark documents as Draft, Confidential, or add your logo. Adjustable opacity. No signup.",
  "percentage-calculator": "Calculate percentage of a number, percentage change between values, and add or subtract a percentage instantly. Free online percentage calculator for students.",
  "photo-resizer": "Resize photos to exact Aadhaar card, PAN card, and passport size online free. Perfect dimensions for Indian government documents.",
  "pomodoro-timer": "Free Pomodoro timer online. 25-minute focus sessions with short and long breaks. Boost productivity instantly.",
  "ppt-to-pdf": "Convert PowerPoint presentations to PDF free online. No signup, browser-only PPT to PDF conversion.",
  "qr-code-generator": "Generate QR codes for URLs, WhatsApp, WiFi, vCards, and SMS. Download as PNG or SVG with no watermark. Free online QR code generator — no signup needed.",
  "random-number": "Generate random numbers, lists, and unique IDs free online. Customizable range and count. Instant results.",
  "rd-calculator": "Calculate recurring deposit maturity, interest earned, and TDS impact. Free RD calculator for Indian banks with RD vs FD comparison. No signup.",
  "regex-tester": "Test and debug regular expressions free online. Real-time match highlighting with explanation.",
  "robots-txt-generator": "Generate a valid robots.txt file for your website free online. Add user-agents, allow/disallow rules, and sitemap URL. Download or copy instantly.",
  "rent-receipt-generator": "Generate professional rent receipt PDFs for HRA tax claims in India. Create single or multi-month receipts with landlord and tenant details. Free download.",
  "roman-numeral-converter": "Convert numbers to Roman numerals or Roman numerals to numbers free online. Instant, accurate conversion both directions. No signup needed.",
  "salary-hike-calculator": "Calculate your new salary after an appraisal hike or find the hike percentage from your target pay. Free salary hike calculator for employees in India.",
  "signature-maker": "Create a digital signature by drawing, typing your name, or uploading an image. Download PNG or JPG or copy to clipboard. Free signature maker for documents.",
  "sip-calculator": "Calculate mutual fund SIP returns with maturity value, total invested, and estimated gains. Free SIP calculator with year-by-year growth projection for India.",
  "sql-formatter": "Format and beautify SQL queries online free. Auto-indent, capitalize keywords, and make long queries readable. No signup, runs in your browser.",
  "stopwatch": "Free online stopwatch with lap timer. Precise timing with milliseconds. Start, stop, lap, and reset instantly.",
  "subnet-calculator": "Free subnet calculator for IPv4 CIDR. Find network address, broadcast, usable hosts, IP range, and subnet mask instantly. No signup needed.",
  "svg-to-png": "Convert SVG to PNG online free at any resolution. Choose transparent or solid background. No signup, conversion happens in your browser.",
  "svg-previewer": "Preview SVG code live in your browser. Paste SVG markup and see it render instantly. Download, prettify, and test on different backgrounds. No signup.",
  "text-case-converter": "Convert text to uppercase, lowercase, title case, camelCase, snake_case and more. Free online text case tool.",
  "text-diff": "Compare two texts and find differences online free. Highlight added, removed, and changed lines instantly.",
  "text-to-speech": "Free text to speech converter. Type or paste text and listen instantly with natural voices. No signup, works directly in your browser.",
  "timezone-converter": "Convert time between time zones free online. Compare multiple cities and find meeting times instantly.",
  "tip-calculator": "Calculate tip amount and split bills between friends free online. Works with USD and INR.",
  "unit-converter": "Convert units instantly — length, weight, temperature, area, speed, volume and more. Free online unit converter with 50+ unit types. No signup, instant results.",
  "url-encoder": "Encode and decode URLs free online. Convert special characters in URLs instantly. Fast, private, browser-only.",
  "uuid-generator": "Generate random UUID v4 identifiers online free. Create one or hundreds at once, with or without hyphens. No signup, runs in your browser.",
  "webp-to-jpg": "Convert WebP images to JPG or PNG free online. Fast, private, browser-only WebP converter. No signup needed.",
  "word-counter": "Free online word counter. Count words, characters, sentences, reading time, and keyword density instantly. Perfect for essays, social media, and SEO. No signup.",
  "word-to-pdf": "Convert Word documents to PDF online free. Fast DOCX to PDF conversion. No signup needed, browser-only processing.",
  "xml-formatter": "Format, beautify and validate XML data free online. Fix XML errors and view structured data instantly.",
  "loan-eligibility": "Check your home, personal or car loan eligibility free online. Based on Indian FOIR guidelines — see max eligible amount and EMI. No signup required.",
  "ppf-calculator": "Calculate PPF maturity amount, interest earned, and year-by-year balance free online. Includes partial withdrawal rules, loan eligibility, and 5-year extension blocks for India.",
  "css-gradient": "Create CSS gradients visually and copy the code instantly. Linear, radial, and conic gradients with live preview and one-click copy. No signup needed.",
  "timestamp-converter": "Convert Unix timestamps to readable dates and back. See current epoch time live. Auto-detects seconds vs milliseconds instantly. No signup needed.",
  "json-to-csv": "Convert JSON arrays to CSV online free. Paste JSON data and download a spreadsheet-ready CSV file instantly. No signup, runs in your browser.",
  "word-to-jpg": "Convert Word documents to JPG images online free. Upload a DOCX file and download as an image. Share docs without editing access. No signup needed.",
  "currency-converter": "Convert currencies with live exchange rates from the European Central Bank. Free online currency converter — USD, EUR, GBP, INR and more. No signup.",
  "crypto-tracker": "Track live cryptocurrency prices free online. Bitcoin, Ethereum, and top 15 cryptos with 24h change, market cap, and USD converter. No signup.",
  "dns-lookup": "Look up DNS records for any domain free online. Check A, AAAA, CNAME, MX, TXT, NS records instantly. Powered by Cloudflare DNS. No signup.",
  "ip-lookup": "Look up any IP address location, ISP, and timezone online free. See your own IP or check any IP address instantly. No signup needed.",
};

export function getToolPageDescription(slug: string): string | undefined {
  return TOOL_PAGE_DESCRIPTIONS[slug];
}
