import Link from "next/link";

const faqs = [
  {
    question: "Can I use this pay stub for a rental application?",
    answer:
      "A pay stub generated by this tool can be used as a reference document to show income, but some landlords and banks may require official pay stubs from your employer or payroll provider. If in doubt, check with the requesting party what documentation format they accept.",
  },
  {
    question: "How accurate are the tax deductions?",
    answer:
      "Federal income tax is estimated based on 2026 tax brackets for single filers. Social Security (6.2%) and Medicare (1.45%) are calculated accurately per IRS rates. State income tax requires manual entry as it varies significantly by state. For payroll tax accuracy, use an official payroll service.",
  },
  {
    question: "Is my pay information safe to enter here?",
    answer:
      "Yes — this tool runs entirely in your browser. No pay data is ever sent to a server. Your information is not stored, logged, or transmitted. Close the browser tab to clear all data.",
  },
  {
    question: "What is the difference between gross pay and net pay?",
    answer:
      "Gross pay is your total earnings before any deductions. Net pay (take-home pay) is what remains after federal tax, FICA (Social Security and Medicare), state tax, health insurance, and other deductions are subtracted. Your paycheck amount reflects net pay.",
  },
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: { "@type": "Answer", text: faq.answer },
  })),
};

export default function PayStubGeneratorGuideUsaContent() {
  return (
    <article className="prose-custom">
      <p>
        Need a pay stub for income documentation? Use our free{" "}
        <Link href="/tools/pay-stub-generator">Pay Stub Generator</Link> — runs
        entirely in your browser with no data sent to servers.
      </p>

      <hr />

      <h2>What Is a Pay Stub?</h2>
      <p>
        A pay stub (earnings statement) records your gross pay, deductions, and
        net pay for a specific pay period. It shows hours worked, tax withholdings,
        and employer contributions.
      </p>

      <hr />

      <h2>What Every US Pay Stub Must Show</h2>
      <ul>
        <li>Gross earnings by type (regular, overtime, bonus)</li>
        <li>Federal income tax withheld</li>
        <li>FICA — Social Security (6.2%) and Medicare (1.45%)</li>
        <li>State income tax (if applicable)</li>
        <li>Net pay (take-home amount)</li>
      </ul>

      <hr />

      <h2>Who Needs a Pay Stub?</h2>
      <p>
        Employees for income verification (rental, loans), freelancers documenting
        earnings, and small business owners maintaining payroll records.
      </p>

      <hr />

      <h2>FICA Deductions Explained</h2>
      <p>
        FICA totals 7.65% of gross pay — 6.2% Social Security (up to $184,500
        wage base in 2026) plus 1.45% Medicare on all wages.
      </p>

      <hr />

      <h2>Is This Pay Stub Official?</h2>
      <p>
        This tool generates reference documents only. Official pay stubs must be
        issued by your employer or payroll provider.
      </p>

      <hr />

      <h2>Privacy Considerations</h2>
      <p>
        Browser-based generators keep pay data on your device. Server-side tools
        may log or store sensitive information. Related:{" "}
        <Link href="/tools/paycheck-calculator">Paycheck Calculator</Link>,{" "}
        <Link href="/tools/w2-vs-1099-calculator">W-2 vs 1099 Calculator</Link>.
        Guides:{" "}
        <Link href="/blog/us-paycheck-calculator-guide">
          US paycheck calculator guide
        </Link>
        ,{" "}
        <Link href="/blog/w2-vs-1099-tax-comparison-guide">
          W-2 vs 1099 tax comparison
        </Link>
        .
      </p>

      <hr />

      <h2>Frequently Asked Questions</h2>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      {faqs.map((faq) => (
        <div key={faq.question}>
          <h3>{faq.question}</h3>
          <p>{faq.answer}</p>
        </div>
      ))}
    </article>
  );
}
